// <auto-generated />
namespace GreekHealthcareNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Office_Homeaddressmaxminlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Office_Homeaddressmaxminlength));
        
        string IMigrationMetadata.Id
        {
            get { return "201912311843125_Office_Home address max, min length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
