// <auto-generated />
namespace GreekHealthcareNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ScripttosetAppointmentStatustoCompleteautomatically : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScripttosetAppointmentStatustoCompleteautomatically));
        
        string IMigrationMetadata.Id
        {
            get { return "202001090747522_Script to set AppointmentStatus to Complete automatically"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
