// <auto-generated />
namespace GreekHealthcareNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateStoredProceduretodeleteunpaidappointments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateStoredProceduretodeleteunpaidappointments));
        
        string IMigrationMetadata.Id
        {
            get { return "202001152330280_Create Stored Procedure to delete unpaid appointments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
